import { Inter } from "next/font/google";

import { Header } from "@/layout/header";
import Provider from "@/components/provider";
import { Toaster } from "@/components/ui/toaster";

import "@/styles/globals.css";
import { ReduxProvider } from "@/components/reduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Provider>
            <Toaster />
            <Header />
            {children}
          </Provider>
        </ReduxProvider>
      </body>
    </html>
  );
}
